/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Admin;
import Model.Person;
import Model.Doctor;
import Model.Resident;
import Model.Hospital;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import Model.Encounter;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Prathmesh Pardeshi
 */
public class LandingFrame extends javax.swing.JFrame {

    /**
     * Creates new form LandingFrame
     */
  Admin admin;
    
    public LandingFrame() {
        initComponents();
        this.lowerPanel=lowerPanel;
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        setBounds(0,0,screenSize.width, screenSize.height);
//        setVisible(true);
        admin = new Admin();
        Resident residence = new Resident("1226","Beacon Street","Boston");
        Person p1 = new Person("Mahika",21,"Female", "NA","NA", residence, false, 130.0, 11.0);
        Person p2 = new Person("Shivani",21,"Female", "Fever","High BP", new Resident("0155", "Massachusett Ave", "Newyork"), true, 170.00d, 67.00d, new ArrayList<>());
        Person p3 = new Person("Swarali",23,"Female", "Head ache","Elbow surgery", new Resident("0224", "Manhattan Ave", "Newyork"), false, 192.0, 80.00d, new ArrayList<>());
        Person p4 = new Person("Neeraj",37,"Male", "diarrhea","Swine Flu", new Resident("1885", "Charles st", "Boston"), false, 130.00d, 60.00d, new ArrayList<>());
        Person p5 = new Person("Atharva",22,"Male", "NA","Allergy", new Resident("0215", "Boylston", "Boston"), true, 150.00d, 40.00d, new ArrayList<>());
        Person p6 = new Person("Chinmay",22,"Male", "Fever","Swine Flu", new Resident("1215", "Roxbury", "Texas"), true, 150.00d, 80.00d, new ArrayList<>());

        ArrayList<Person> personDirectory = new ArrayList<>();
        personDirectory.add(p1);
        personDirectory.add(p2);
        personDirectory.add(p3);
        personDirectory.add(p4);
        personDirectory.add(p5);
        personDirectory.add(p6);
        admin.setPersonDirectory(personDirectory);
        ArrayList<Person> patientDirectory = new ArrayList<>();
        admin.setPatientDirectory(patientDirectory);
        
        Doctor d1 = new Doctor("Micheal", "Boston", 111);
        Doctor d2 = new Doctor("Ryan", "Neywork", 114);
        Doctor d3 = new Doctor("Dwight", "Boston", 115);
        Doctor d4 = new Doctor("Pamela", "Texas", 117);
        
        ArrayList<Doctor> doctorDirectory = new ArrayList<>();
        doctorDirectory.add(d1);
        doctorDirectory.add(d2);
        doctorDirectory.add(d3);
        doctorDirectory.add(d4);
        admin.setDoctorDirectory(doctorDirectory);
        
        Hospital h1 = new Hospital("Nobel", "Fenway", 100, "Boston");
        Hospital h2 = new Hospital("Apollo", "Beacon Hill", 105, "Boston");
        Hospital h3 = new Hospital("Apollo", "Manhattan St", 125, "Newyork");
        Hospital h4 = new Hospital("Rockafella", "Big Apple", 105, "Newyork");
        Hospital h5 = new Hospital("National", "Riverside", 130, "Boston");
        
        
        ArrayList<Hospital> hospitalDirectory = new ArrayList<>();
        hospitalDirectory.add(h1);
        hospitalDirectory.add(h2);
        hospitalDirectory.add(h3);
        hospitalDirectory.add(h4);
        hospitalDirectory.add(h5);
        admin.setHospitalDirectory(hospitalDirectory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        upperPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lowerPanel = new javax.swing.JPanel();
        MainPanelScreen = new javax.swing.JPanel();
        SystemAdmin = new javax.swing.JButton();
        Patient = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        CommunityAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NewUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        upperPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel2.setText("BOSTON CITY HEALTH CARE");

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSplitPane1.setTopComponent(upperPanel);

        lowerPanel.setBackground(new java.awt.Color(204, 204, 255));
        lowerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lowerPanel.setLayout(new java.awt.CardLayout());

        MainPanelScreen.setBackground(new java.awt.Color(204, 255, 255));

        SystemAdmin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        SystemAdmin.setText("SYSTEM ADMIN");
        SystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemAdminActionPerformed(evt);
            }
        });

        Patient.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Patient.setText("PATIENT");
        Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientActionPerformed(evt);
            }
        });

        Doctor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Doctor.setText("DOCTOR");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });

        CommunityAdmin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        CommunityAdmin.setText("COMMUNITY ADMIN");
        CommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityAdminActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Please select a user login type - ");

        NewUser.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        NewUser.setText("NEW USER");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelScreenLayout = new javax.swing.GroupLayout(MainPanelScreen);
        MainPanelScreen.setLayout(MainPanelScreenLayout);
        MainPanelScreenLayout.setHorizontalGroup(
            MainPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelScreenLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(MainPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(MainPanelScreenLayout.createSequentialGroup()
                        .addComponent(SystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(CommunityAdmin))
                    .addGroup(MainPanelScreenLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(NewUser)))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        MainPanelScreenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CommunityAdmin, Doctor, NewUser, Patient, SystemAdmin});

        MainPanelScreenLayout.setVerticalGroup(
            MainPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelScreenLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addGroup(MainPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SystemAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(MainPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUser))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        MainPanelScreenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CommunityAdmin, Doctor, NewUser, Patient, SystemAdmin});

        lowerPanel.add(MainPanelScreen, "card2");

        jSplitPane1.setRightComponent(lowerPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityAdminActionPerformed
        CommunityAdminLogin CommunityLoginPage = new CommunityAdminLogin(lowerPanel,admin );
        lowerPanel.add("CommunityAdmin",CommunityLoginPage);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);         // TODO add your handling code here:
    }//GEN-LAST:event_CommunityAdminActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        DoctorLoginPage DoctorLoginPage = new DoctorLoginPage(lowerPanel,admin);
        lowerPanel.add("DoctorAdmin",DoctorLoginPage);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);             // TODO add your handling code here:
    }//GEN-LAST:event_DoctorActionPerformed

    private void PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientActionPerformed
        PatientLogin PatientLoginPage = new PatientLogin(lowerPanel,admin);
        lowerPanel.add("PatientAdmin",PatientLoginPage);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_PatientActionPerformed

    private void SystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemAdminActionPerformed
        // TODO add your handling code here:
        SystemLoginPage adminLoginPage = new SystemLoginPage(lowerPanel, admin);
        lowerPanel.add("AdminWindow", adminLoginPage);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);
    }//GEN-LAST:event_SystemAdminActionPerformed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        // TODO add your handling code here:
        NewUser newUserPage = new NewUser(lowerPanel,admin);
        lowerPanel.add("PatientAdmin",newUserPage);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);
    }//GEN-LAST:event_NewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommunityAdmin;
    private javax.swing.JButton Doctor;
    private javax.swing.JPanel MainPanelScreen;
    private javax.swing.JButton NewUser;
    private javax.swing.JButton Patient;
    private javax.swing.JButton SystemAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
