/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Assignment2_model.Patient;
import Assignment2_model.PatientDirectory;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author prath
 */
public class NewPatient extends javax.swing.JPanel {

    PatientDirectory ptDirectory;
    /**
     * Creates new form NewPatient
     */
    public NewPatient(PatientDirectory ptDirectory) {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,screenSize.width, screenSize.height);
        setVisible(true);
        this.ptDirectory = ptDirectory;
        Patient newPt2 = ptDirectory.addNewPatient();
        prepopulateTable(newPt2);
        PatientTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PtIDText = new javax.swing.JTextField();
        PtNameText = new javax.swing.JTextField();
        PtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PtCity = new javax.swing.JTextField();
        PtCommunity = new javax.swing.JTextField();
        PtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Patient ID");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        PtIDText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PtIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PtIDTextActionPerformed(evt);
            }
        });

        PtNameText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PtAge.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setText("City");

        jLabel5.setText("Community");

        jLabel6.setText("Address");

        PtCity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PtCommunity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PtAddress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "City", "Community", "Address"
            }
        ));
        jScrollPane1.setViewportView(PatientTable);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Add new Patient :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PtIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PtNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(PtAge))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PtCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(PtCity)
                            .addComponent(PtAddress)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PtIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(PtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PtNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(PtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(PtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PtIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PtIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PtIDTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ptIDtxt = PtIDText.getText();
        String ptNametxt = PtNameText.getText();
        int ptAgetxt= Integer.parseInt(PtAge.getText());
        String ptCitytxt = PtCity.getText();
        String ptCommunitytxt = PtCommunity.getText();
        String ptAddresstxt = PtAddress.getText();

        Patient newPt = ptDirectory.addNewPatient();
        
        newPt.setPtID(ptCitytxt);
        newPt.setPtName(ptNametxt);
        newPt.setPtAge(ptAgetxt);
        newPt.setPtAddress(ptAddresstxt);
        newPt.setPtCommunity(ptCommunitytxt);
        newPt.setPtCity(ptCitytxt);
        
        JOptionPane.showMessageDialog(this, "Product info saved");
        
        PtIDText.setText("");
        PtAge.setText("");
        PtCity.setText("");
        PtCommunity.setText("");
        PtNameText.setText("");
        PtAddress.setText("");
        
        PatientTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PatientTable;
    private javax.swing.JTextField PtAddress;
    private javax.swing.JTextField PtAge;
    private javax.swing.JTextField PtCity;
    private javax.swing.JTextField PtCommunity;
    private javax.swing.JTextField PtIDText;
    private javax.swing.JTextField PtNameText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void prepopulateTable(Patient prePt){
        prePt.setPtID("4324");
        prePt.setPtName("Peter");
        prePt.setPtAge(23);
        prePt.setPtAddress("1167 Fenway");
        prePt.setPtCommunity("Christian");
        prePt.setPtCity("Boston");
        
        PatientTable();
    }
    private void PatientTable(){
        DefaultTableModel model = (DefaultTableModel) PatientTable.getModel();
        
        model.setRowCount(0);
//        int empCount = 1;
        
        for(Patient pt : ptDirectory.getPatientData()){
            Object[] tableRow = new Object[6];
            tableRow[0] = pt;
//            tableRow[1] = pt.getPtID();
            tableRow[1] = pt.getPtName();
            tableRow[2] = pt.getPtAge();
            tableRow[3] = pt.getPtCity();
            tableRow[4] = pt.getPtCommunity();
            tableRow[5] = pt.getPtAddress();
            
            model.addRow(tableRow);
            
        }
    }

}

