/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Admin;
import Model.Person;
import Model.Resident;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Prathmesh Pardeshi
 */
public class PatientMainScreen extends javax.swing.JPanel {
    //Admin admin;
    //Person person;
    Admin admin;
    JPanel lowerPanel;
    private ArrayList<Person> patientDir;
    private ArrayList<Person> personDir;
    /**
     * Creates new form PatientMainScreen
     */
    public PatientMainScreen(JPanel lowerPanel,Admin admin) {
               initComponents();
        this.lowerPanel =lowerPanel;
        this.admin = admin;
        personDir = admin.getPersonDirectory();
        patientDir = admin.getPatientDirectory();
        loadpatientTable();
        UniqueId.setVisible(false);
        PatientId.setVisible(false);
        ViewPId.setVisible(false);
        DefaultTableModel model3 = (DefaultTableModel) vitalsTable.getModel();
        model3.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        viewEncounterButton = new javax.swing.JButton();
        BackMain = new javax.swing.JButton();
        ViewVitals = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitalsTable = new javax.swing.JTable();
        PatientId = new javax.swing.JTextField();
        UniqueId = new javax.swing.JLabel();
        ViewPId = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("PATIENT DIRECTORY");

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Age", "Gender", "Residence", "isPatient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(patientTable);

        viewEncounterButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        viewEncounterButton.setText("VIEW APPOINTMENTS");
        viewEncounterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEncounterButtonActionPerformed(evt);
            }
        });

        BackMain.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BackMain.setText("LOGOUT");
        BackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMainActionPerformed(evt);
            }
        });

        ViewVitals.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ViewVitals.setText("VIEW VITALS");
        ViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVitalsActionPerformed(evt);
            }
        });

        vitalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "illness", "Past illness", "BP", "Pulse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vitalsTable);

        PatientId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PatientId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientIdMouseClicked(evt);
            }
        });

        UniqueId.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        UniqueId.setText("Enter Your Patient ID:");

        ViewPId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ViewPId.setText("VIEW");
        ViewPId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(viewEncounterButton)
                            .addGap(62, 62, 62)
                            .addComponent(ViewVitals)
                            .addGap(67, 67, 67)
                            .addComponent(BackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(202, 202, 202)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(ViewPId)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UniqueId)
                            .addGap(36, 36, 36)
                            .addComponent(PatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ViewVitals, viewEncounterButton});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEncounterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewVitals))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UniqueId)
                    .addComponent(ViewPId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(421, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ViewVitals, viewEncounterButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1174, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewEncounterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEncounterButtonActionPerformed
        // TODO add your handling code here:
        int row = patientTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a patient record!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person person = (Person)patientTable.getValueAt(row, 0);
        PatientViewEncounter viewEncounterJPanel = new PatientViewEncounter(lowerPanel,person,admin);
        lowerPanel.add("EncounterPanel",viewEncounterJPanel);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);
    }//GEN-LAST:event_viewEncounterButtonActionPerformed

    private void BackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMainActionPerformed
          // TODO add your handling code here:
          this.patientDir=admin.getPatientDirectory();
          CommonScreen CommanScreen=new CommonScreen(lowerPanel,admin,patientDir,personDir);
          lowerPanel.add("CommanScreen",CommanScreen);
           CardLayout cardLayout = (CardLayout)lowerPanel.getLayout();
         cardLayout.next(lowerPanel);
    }//GEN-LAST:event_BackMainActionPerformed

    private void ViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVitalsActionPerformed
        // TODO add your handling code here:
        int rowCount = vitalsTable.getRowCount();
        DefaultTableModel model1 = (DefaultTableModel) vitalsTable.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model1.removeRow(i);
        } 
        
        int selectedRowIndex = patientTable.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        UniqueId.setVisible(true);
        PatientId.setVisible(true);
        ViewPId.setVisible(true);
    }//GEN-LAST:event_ViewVitalsActionPerformed

    private void ViewPIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPIdActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = patientTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        Person selectedPat = (Person) model.getValueAt(selectedRowIndex, 0);
        if(PatientId.getText().equals(String.valueOf(selectedPat.getId()))){
            loadVitalsTable(selectedPat);
        }
        else{
            JOptionPane.showMessageDialog(this, "Incorrect Patient ID");
            return;
        }
    }//GEN-LAST:event_ViewPIdActionPerformed

    private void PatientIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientIdMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model3 = (DefaultTableModel) vitalsTable.getModel();
        model3.setRowCount(0);
    }//GEN-LAST:event_PatientIdMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackMain;
    private javax.swing.JTextField PatientId;
    private javax.swing.JLabel UniqueId;
    private javax.swing.JButton ViewPId;
    private javax.swing.JButton ViewVitals;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable patientTable;
    private javax.swing.JButton viewEncounterButton;
    private javax.swing.JTable vitalsTable;
    // End of variables declaration//GEN-END:variables

    private void loadpatientTable() {
        int rowCount = patientTable.getRowCount();
        ArrayList<Person> patientDirectory = new ArrayList<>();

        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }
        for (Person p : admin.getPersonDirectory()) {
        if (p.isIsPatient()==true){
        System.out.println(p.isIsPatient());
            patientDirectory.add(p);
            }
        }
        admin.setPatientDirectory(patientDirectory);

        for (Person p : admin.getPatientDirectory()) {
            Object row[] = new Object[10];
//            row[0] = p.getId();
            row[0] = p;
            row[1]= p.getGender();
            row[2] = p.getAge();
            Resident residence = p.getResidence();
            row[3] = residence.getHouse()+" "+residence.getCommunity()+", "+residence.getCity();
            row[4] = p.isIsPatient();
            model.addRow(row);
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
    
    private void loadVitalsTable(Person selectedPat) {
        DefaultTableModel model1 = (DefaultTableModel) vitalsTable.getModel();
        Object row[] = new Object[4];
            row[0]= selectedPat.getIllness();
            row[1] = selectedPat.getHB();
            row[2]=selectedPat.getBloodPressure();
            row[3]= selectedPat.getPastIllness();
            
            model1.addRow(row);
    }
}