/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Assignment1_model.Employee;
import Assignment1_model.EmployeeData;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author prath
 */
public class CreateEmpPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmpPanel
     */
    
    EmployeeData employeeData;
    
    public CreateEmpPanel(EmployeeData employeeData) {
        initComponents();
        this.employeeData = employeeData;
        
        EmpStartDate.setToolTipText("<html><b><font color=red>"+"Please enter date in mm/dd/yyyy format"+ "</font></b></html>");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmpName = new javax.swing.JTextField();
        EmpId = new javax.swing.JTextField();
        EmpStartDate = new javax.swing.JTextField();
        EmpLevel = new javax.swing.JTextField();
        EmpTeamInfo = new javax.swing.JTextField();
        EmpContactNum = new javax.swing.JTextField();
        EmpEmail = new javax.swing.JTextField();
        EmpAge = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        EmpPosition = new javax.swing.JTextField();
        EmpPhoto = new javax.swing.JLabel();
        AttachImg = new javax.swing.JButton();
        EmpGender = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1163, 843));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Fill the following information:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Employee ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Age:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Start date:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Team info:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Contact No:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Email:");

        EmpName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpName.setPreferredSize(new java.awt.Dimension(325, 50));
        EmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNameActionPerformed(evt);
            }
        });
        EmpName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmpNameKeyReleased(evt);
            }
        });

        EmpId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpId.setPreferredSize(new java.awt.Dimension(325, 50));
        EmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdActionPerformed(evt);
            }
        });

        EmpStartDate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpStartDate.setPreferredSize(new java.awt.Dimension(325, 50));
        EmpStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpStartDateActionPerformed(evt);
            }
        });

        EmpLevel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpLevel.setPreferredSize(new java.awt.Dimension(325, 50));

        EmpTeamInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpTeamInfo.setPreferredSize(new java.awt.Dimension(325, 50));

        EmpContactNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpContactNum.setMinimumSize(new java.awt.Dimension(325, 50));
        EmpContactNum.setPreferredSize(new java.awt.Dimension(325, 50));

        EmpEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpEmail.setMinimumSize(new java.awt.Dimension(325, 50));
        EmpEmail.setPreferredSize(new java.awt.Dimension(325, 50));

        EmpAge.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpAge.setPreferredSize(new java.awt.Dimension(96, 50));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Level:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Position Title:");

        EmpPosition.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpPosition.setPreferredSize(new java.awt.Dimension(325, 50));

        AttachImg.setText("Attach Image");
        AttachImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachImgActionPerformed(evt);
            }
        });

        EmpGender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmpAge, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(EmpName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel14))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EmpPosition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addComponent(EmpTeamInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EmpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(EmpPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(252, 252, 252))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(AttachImg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(EmpAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(EmpContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(EmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(EmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(AttachImg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmpPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(100, 100, 100)))
                .addGap(38, 38, 38)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EmpEmail, EmpGender});

    }// </editor-fold>//GEN-END:initComponents

    private void EmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpNameActionPerformed

    private void EmpStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpStartDateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpStartDateActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        boolean empInfoValidation = this.empInfoValidation();
        
        if(empInfoValidation){
        String empNametxt = EmpName.getText();
        String empIdtxt= EmpId.getText();
        String empContacttxt = EmpContactNum.getText();
        String empEmailtxt = EmpEmail.getText();
        String empGendertxt = EmpGender.getText();
        String empAgetxt = EmpAge.getText();
        String empLeveltxt = EmpLevel.getText();
        String empPositiontxt = EmpPosition.getText();
        String empStartDatetxt = EmpStartDate.getText();
        String empTeamInfotxt = EmpTeamInfo.getText();
        ImageIcon empImg = (ImageIcon) EmpPhoto.getIcon();
        
        
        Employee emp = employeeData.addNewEmployee();
        
        emp.setEmpName(empNametxt);
        emp.setEmpId(empIdtxt);
        emp.setEmpContactNum(empContacttxt);
        emp.setEmpEmail(empEmailtxt);
        emp.setEmpGender(empGendertxt);
        emp.setEmpAge(empAgetxt);
        emp.setEmpLevel(empLeveltxt);
        emp.setEmpPosition(empPositiontxt);
        emp.setEmpLevel(empLeveltxt);
        emp.setEmpTeamInfo(empTeamInfotxt);
        emp.setEmpStartDate(empStartDatetxt);
        emp.setEmpImage(empImg);
        
       
        JOptionPane.showMessageDialog(this, "Product info saved");
        
        EmpName.setText("");
        EmpId.setText("");
        EmpContactNum.setText("");
        EmpEmail.setText("");
        EmpLevel.setText("");
        EmpPosition.setText("");
        EmpTeamInfo.setText("");
        EmpStartDate.setText("");
        EmpAge.setText("");
        EmpPhoto.setIcon(null);
        EmpGender.setText("");
        }
       
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void EmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIdActionPerformed

    private void AttachImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachImgActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        int selectedImg = fileChooser.showOpenDialog(null);
        if(selectedImg == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getselectedImg = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getselectedImg);
            ImageIcon imIco = new ImageIcon(getselectedImg);
            EmpPhoto.setIcon(imIco);
        }
    }//GEN-LAST:event_AttachImgActionPerformed

    private void EmpNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNameKeyReleased
        // TODO add your handling code here:
        String eName = EmpName.getText();
        if (!eName.equals("")) {
            SaveButton.setEnabled(true);
        } else {
            SaveButton.setEnabled(false);
        }

    }//GEN-LAST:event_EmpNameKeyReleased

    private void EmpGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttachImg;
    private javax.swing.JTextField EmpAge;
    private javax.swing.JTextField EmpContactNum;
    private javax.swing.JTextField EmpEmail;
    private javax.swing.JTextField EmpGender;
    private javax.swing.JTextField EmpId;
    private javax.swing.JTextField EmpLevel;
    private javax.swing.JTextField EmpName;
    private javax.swing.JLabel EmpPhoto;
    private javax.swing.JTextField EmpPosition;
    private javax.swing.JTextField EmpStartDate;
    private javax.swing.JTextField EmpTeamInfo;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    
    private boolean empInfoValidation(){
        if(!DateValidation(EmpStartDate.getText())){
            JOptionPane.showMessageDialog(this, "Enter valid date");
            return false;
        }
        
        if(!EmpContactNum.getText().matches("[0-9]+") || EmpContactNum.getText().length()!=10){
            JOptionPane.showMessageDialog(this, "Enter valid 10 digit phone number");
            return false;
        }
        return true;
    }
    
    public static boolean DateValidation(String startingDate){
        if(startingDate.trim().equals("")){
            return true;
        }
        else{
            SimpleDateFormat sdformat = new SimpleDateFormat("mm/dd/yyyy");
            sdformat.setLenient(false);
            try{
                Date JDate = sdformat.parse(startingDate);
            }
            catch(ParseException e){
                return false;
            }
            return true;
        }
    }
}


